services:
  db:
    env_file:
      - ./.env
    image: mysql:8.0
    container_name: no_control_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      TZ: America/Sao_Paulo
    ports:
      - "${DB_PORT}:3306"
networks:
  database_network:
    driver: bridge
